package de.axone.enums;

public enum DiskControlType {
    RADIALITY_OF_STYLUS_SPEED,
    ALIGNMENT_OF_SPEED_ACTIVITY_AND_DISTANCE_STYLES,
    STYLUS_POSITION_DISTANCE,
    CORRESPONDING_CLOCK_AND_DISC,
    SPEED_CONTROL,
}
