package de.axone.enums;

public enum ValueType {
    CONTROLS_FOR_NORMAL_TEST_CONDITIONS,
    ADMINISTRATIVE_CHECKS,
    INSPECTION_OF_SYSTEM_AND_TACHOGRAPH_SEALS,
    INSPECTION_OF_INSTALLATION_SEALS_AND_SEALING,
    CONTROL_OF_ACTIVITY_ON_TEST_DISK,

}
